cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "//src/communication:odrive_socket",
        "//src/controller:low_level_controller",
        "//src/controller:low_level_types",
        "@spdlog//:spdlog",
    ],
)